name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-model:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos]
        version:
          - { python: '3.12', resolution: highest }
          - { python: '3.12', resolution: lowest-direct }
        model:
          - { name: fairchem-legacy, test_path: "tests/models/test_fairchem_legacy.py" }
        exclude:
          - version: { python: '3.13', resolution: lowest-direct }
            model: { name: orb, test_path: "tests/models/test_orb.py" }
          - version: { python: '3.13', resolution: highest }
            model: { name: orb, test_path: "tests/models/test_orb.py" }
          - version: { python: '3.13', resolution: lowest-direct }
            model: { name: fairchem-legacy, test_path: "tests/models/test_fairchem_legacy.py" }
          - version: { python: '3.13', resolution: highest }
            model: { name: fairchem-legacy, test_path: "tests/models/test_fairchem_legacy.py" }
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Check out fairchem repository
        if: ${{ matrix.model.name == 'fairchem-legacy' }}
        uses: actions/checkout@v4
        with:
          repository: FAIR-Chem/fairchem
          path: fairchem-repo
          ref: fairchem_core-1.10.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version.python }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install HDF5 on macOS
        if: runner.os == 'macOS'
        run: brew install hdf5

      - name: Install legacy fairchem repository and dependencies
        if: ${{ matrix.model.name == 'fairchem-legacy' }}
        run: |
          if [ -f fairchem-repo/packages/requirements.txt ]; then
            uv pip install -r fairchem-repo/packages/requirements.txt --system
          fi
          if [ -f fairchem-repo/packages/requirements-optional.txt ]; then
            uv pip install -r fairchem-repo/packages/requirements-optional.txt --system
          fi
          uv pip install -e fairchem-repo/packages/fairchem-core[dev] --system
          uv pip install -e ".[test]" --resolution=${{ matrix.version.resolution }} --system


      - name: Install torch_sim with model dependencies
        if: ${{ matrix.model.name != 'fairchem-legacy' }}
        run: |
          # always use numpy>=2 with Python 3.13
          if [ "${{ matrix.version.python }}" = "3.13" ]; then
            uv pip install -e ".[test,${{ matrix.model.name }}]" "numpy>=2" --resolution=${{ matrix.version.resolution }} --system
          else
            uv pip install -e ".[test,${{ matrix.model.name }}]" --resolution=${{ matrix.version.resolution }} --system
          fi

      - name: Run ${{ matrix.model.test_path }} tests
        env:
          HF_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          if [[ "${{ matrix.model.name }}" == *"fairchem"* ]]; then
            uv pip install huggingface_hub --system
          fi
          pytest -vv -ra -rs --cov=torch_sim --cov-report=xml ${{ matrix.model.test_path }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: radical-ai/torch-sim
